set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[2 q'
set -as terminal-overrides ',*:Sm=\E[22m'
set -g escape-time 10
set -g focus-events on
set -g history-limit 50000
set -g mouse on
set -g set-clipboard on
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1
set -w -g automatic-rename on
set -w -g allow-rename off
set -g detach-on-destroy off
set -g set-titles on
set -g display-panes-time 4000
set -g display-time 4000
set -g status-interval 5
set -g status-left-length 40
set -g status-right-length 150
set -g status-keys vi
set -w -g mode-keys vi
set -g focus-events on
set -g -a status-left '#[fg=#9A348E,bold] #S '
set -g -a status-right '#[fg=#9A348E,bold] %Y-%m-%d %H:%M '
set -g -a status-right '#[fg=blue,bold] #(uptime | cut -d" " -f4-6 | cut -d"," -f1) '
set -g status-style 'fg=#9A348E,bg=#1e1e2e'
set -w -a window-status-current-format '#[fg=#1e1e2e,bg=#9A348E,bold] #I #W '
set -w -a window-status-format '#[fg=#cdd6f4,bg=#313244] #I #W '
set -g -a status-left-style 'fg=#1e1e2e,bg=#9A348E'
set -g -a status-right-style 'fg=#9A348E,bg=#1e1e2e'
set -g -a pane-active-border-style 'fg=#9A348E'
set -g -a pane-border-style 'fg=#313244'
set -g -a message-style 'fg=#1e1e2e,bg=#9A348E'
set -g -a message-command-style 'fg=#cdd6f4,bg=#313244'

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind P paste-buffer
bind-key -T prefix X confirm-before -p "kill pane #P? (y/n)" kill-pane
bind-key -T prefix Q kill-pane
bind-key -T prefix x confirm-before -p "kill pane #P? (y/n)" kill-pane

run-shell 'tmux setenv -g TMUX_PLUGIN_MANAGER_PATH ~/.tmux/plugins/'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-vim 'session'
run '~/.tmux/plugins/tpm/tpm'
